package com.example.applicationstb.model

import android.net.Uri
import android.util.Log
import com.example.applicationstb.localdatabase.*
import kotlinx.serialization.json.Json
import java.util.*


open class DemontageMoteur(
    idFiche: String,
    numDevis: String?,
    numFiche: String?,
    type: Long?,
    statut: Long?,
    client: Client?,
    contact: String?,
    telContact: String?,
    techniciens: Array<User>?,
    resp: User?,
    dateDebut: Date?,
    dureeTotale: Long?,
    observation: String?,
    photos: Array<String>?,
    var typeFicheDemontage: Int?,
    open var typeMoteur:String?,
    open var marque: String?,
    open var numSerie: String?,
    open var puissance: Float?,
    open var bride: Float?,
    open var vitesse : Float?,
    open var arbreSortantEntrant:Boolean?, //arbre sortant ou rentrant
    open var accouplement:Boolean?,
    open var coteAccouplement:String?,
    open var clavette: Boolean?,
    open var aspect:Int?,
    open var aspectInterieur:Int?,
    open var couplage:String?,
    open var flasqueAvant: Int?,
    open var flasqueArriere: Int?,
    open var porteeRAvant: Int?,
    open var porteeRArriere:  Int?,
    open var boutArbre: Boolean?,
    open var rondelleElastique: Boolean?,
    open var refRoulementAvant: Array<String>?,
    open var refRoulementArriere: Array<String>?,
    open var typeRoulementAvant: Array<String>?,
    open var typeRoulementArriere: Array<String>?,
    open var refJointAvant: String?,
    open var refJointArriere: String?,
    open var typeJointAvant: Boolean?,
    open var typeJointArriere: Boolean?,
    open var ventilateur: Int?,
    open var capotV: Int?,
    open var socleBoiteABorne : Int?,
    open var capotBoiteABorne : Int?,
    open var plaqueABorne : Int?,
    open var presenceSondes: Boolean ?,
    open var typeSondes: String?,
    open var equilibrage: Boolean?,
    open var peinture : String?,
) : Fiche(
    idFiche,
    numDevis,
    numFiche,
    type,
    statut,
    client,
    contact,
    telContact,
    techniciens,
    resp,
    dateDebut,
    dureeTotale,
    observation,
    photos
) {
}

class DemontagePompe(
    idFiche: String,
    numDevis: String?,
    numFiche: String?,
    type: Long?,
    statut: Long?,
    client: Client?,
    contact: String?,
    telContact: String?,
    techniciens: Array<User>?,
    resp: User?,
    dateDebut: Date?,
    dureeTotale: Long?,
    observation: String?,
    photos: Array<String>?,
    typeMoteur:String?,
    marque: String?,
    numSerie: String?,
    puissance: Float?,
    bride: Float?,
    vitesse: Float?,
    arbreSortantEntrant: Boolean?, //arbre sortant ou rentrant
    accouplement: Boolean?,
    coteAccouplement: String?,
    clavette: Boolean?,
    aspect: Int?,
    aspectInterieur: Int?,
    couplage: String?,
    flasqueAvant: Int?,
    flasqueArriere: Int?,
    porteeRAvant: Int?,
    porteeRArriere: Int?,
    boutArbre: Boolean?,
    rondelleElastique: Boolean?,
    refRoulementAvant: Array<String>?,
    refRoulementArriere: Array<String>?,
    typeRoulementAvant: Array<String>?,
    typeRoulementArriere: Array<String>?,
    refJointAvant: String?,
    refJointArriere: String?,
    typeJointAvant: Boolean?,
    typeJointArriere: Boolean?,
    ventilateur: Int?,
    capotV: Int?,
    socleBoiteABorne: Int?,
    capotBoiteABorne: Int?,
    plaqueABorne: Int?,
    presenceSondes: Boolean?,
    typeSondes: String?,
    equilibrage: Boolean?,
    peinture: String?,
    var fluide: String?,
    var sensRotation: Boolean?,
    var typeRessort: Int?,
    var typeJoint: String?,
    var matiere: Int?,
    var diametreArbre:String?,
    var diametreExtPR:String?,
    var diametreExtPF:String?,
    var epaisseurPF:String?,
    var longueurRotativeNonComprimee:String?,
    var longueurRotativeComprimee:String?,
    var longueurRotativeTravail:String?
) : DemontageMoteur(
    idFiche,
    numDevis,
    numFiche,
    type,
    statut,
    client,
    contact,
    telContact,
    techniciens,
    resp,
    dateDebut,
    dureeTotale,
    observation,
    photos,
    1,
    typeMoteur,
    marque,
    numSerie,
    puissance,
    bride,
    vitesse,
    arbreSortantEntrant, //arbre sortant ou rentrant
    accouplement,
    coteAccouplement,
    clavette,
    aspect,
    aspectInterieur,
    couplage,
    flasqueAvant,
    flasqueArriere,
    porteeRAvant,
    porteeRArriere,
    boutArbre,
    rondelleElastique,
    refRoulementAvant,
    refRoulementArriere,
    typeRoulementAvant,
    typeRoulementArriere,
    refJointAvant,
    refJointArriere,
    typeJointAvant,
    typeJointArriere,
    ventilateur,
    capotV,
    socleBoiteABorne,
    capotBoiteABorne,
    plaqueABorne,
    presenceSondes,
    typeSondes,
    equilibrage,
    peinture
)
    {
    fun toEntity(): DemoPompeEntity{
        return DemoPompeEntity(
            _id,
            numDevis,
            numFiche,
            status,
            client!!._id,
            contact,
            telContact,
            dateDebut,
            dureeTotale,
            observations,
            photos,
            1,
            typeMoteur,
            marque,
            numSerie,
            fluide,
            sensRotation,
            typeRessort,
            typeJoint,
            matiere,
            diametreArbre,
            diametreExtPR,
            diametreExtPF,
            epaisseurPF,
            longueurRotativeNonComprimee,
            longueurRotativeComprimee,
            longueurRotativeTravail
        )
    }
}

class DemontageMonophase(
    idFiche: String,
    numDevis: String?,
    numFiche: String?,
    type: Long?,
    statut: Long?,
    client: Client?,
    contact: String?,
    telContact: String?,
    techniciens: Array<User>?,
    resp: User?,
    dateDebut: Date?,
    dureeTotale: Long?,
    observation: String?,
    photos: Array<String>?,
    typeMoteur: String?,
    marque: String?,
    numSerie: String?,
    puissance: Float?,
    bride: Float?,
    vitesse: Float?,
    arbreSortantEntrant: Boolean?, //arbre sortant ou rentrant
    accouplement: Boolean?,
    coteAccouplement: String?,
    clavette: Boolean?,
    aspect: Int?,
    aspectInterieur: Int?,
    couplage: String?,
    flasqueAvant: Int?,
    flasqueArriere: Int?,
    porteeRAvant: Int?,
    porteeRArriere: Int?,
    boutArbre: Boolean?,
    rondelleElastique: Boolean?,
    refRoulementAvant: Array<String>?,
    refRoulementArriere: Array<String>?,
    typeRoulementAvant: Array<String>?,
    typeRoulementArriere: Array<String>?,
    refJointAvant: String?,
    refJointArriere: String?,
    typeJointAvant: Boolean?,
    typeJointArriere: Boolean?,
    ventilateur: Int?,
    capotV: Int?,
    socleBoiteABorne: Int?,
    capotBoiteABorne: Int?,
    plaqueABorne: Int?,
    presenceSondes: Boolean?,
    typeSondes: String?,
    equilibrage: Boolean?,
    peinture: String?,
    var isolementPhaseMasse: Float?,
    var resistanceTravail	: Float?,
    var resistanceDemarrage	: Float?,
    var valeurCondensateur	: Float?,
    var tension	: Float?,
    var intensite	: Float?
) : DemontageMoteur(
    idFiche,
    numDevis,
    numFiche,
    type,
    statut,
    client,
    contact,
    telContact,
    techniciens,
    resp,
    dateDebut,
    dureeTotale,
    observation,
    photos,
    2,
    typeMoteur,
    marque,
    numSerie,
    puissance,
    bride,
    vitesse,
    arbreSortantEntrant, //arbre sortant ou rentrant
    accouplement,
    coteAccouplement,
    clavette,
    aspect,
    aspectInterieur,
    couplage,
    flasqueAvant,
    flasqueArriere,
    porteeRAvant,
    porteeRArriere,
    boutArbre,
    rondelleElastique,
    refRoulementAvant,
    refRoulementArriere,
    typeRoulementAvant,
    typeRoulementArriere,
    refJointAvant,
    refJointArriere,
    typeJointAvant,
    typeJointArriere,
    ventilateur,
    capotV,
    socleBoiteABorne,
    capotBoiteABorne,
    plaqueABorne,
    presenceSondes,
    typeSondes,
    equilibrage,
    peinture
) {
    fun toEntity() : DemontageMonophaseEntity{
        return DemontageMonophaseEntity(
            _id,
            numDevis,
            numFiche,
            status,
            client!!._id,
            contact,
            telContact,
            dateDebut,
            dureeTotale,
            observations,
            photos,
            2,
            typeMoteur,
            marque,
            numSerie,
            puissance,
            bride,
            vitesse,
            arbreSortantEntrant,
            accouplement,
            coteAccouplement,
            clavette,
            aspect,
            aspectInterieur,
            couplage,
            flasqueAvant,
            flasqueArriere,
            porteeRArriere,
            porteeRAvant,
            boutArbre,
            rondelleElastique,
            refRoulementAvant,
            refRoulementArriere,
            typeRoulementAvant,
            typeRoulementArriere,
            refJointAvant,
            refJointArriere,
            typeJointAvant,
            typeJointArriere,
            ventilateur,
            capotV,
            socleBoiteABorne,
            capotBoiteABorne,
            plaqueABorne,
            presenceSondes,
            typeSondes,
            equilibrage,
            peinture,
            isolementPhaseMasse,
            resistanceTravail	,
            resistanceDemarrage	,
            valeurCondensateur	,
            tension	,
            intensite
        )
    }
}

class Triphase(
    idFiche: String,
    numDevis: String?,
    numFiche: String?,
    type: Long?,
    statut: Long?,
    client: Client?,
    contact: String?,
    telContact: String?,
    techniciens: Array<User>?,
    resp: User?,
    dateDebut: Date?,
    dureeTotale: Long?,
    observation: String?,
    photos: Array<String>?,
    typeMoteur: String?,
    marque: String?,
    numSerie: String?,
    puissance: Float?,
    bride: Float?,
    vitesse: Float?,
    arbreSortantEntrant: Boolean?, //arbre sortant ou rentrant
    accouplement: Boolean?,
    coteAccouplement: String?,
    clavette: Boolean?,
    aspect: Int?,
    aspectInterieur: Int?,
    couplage: String?,
    flasqueAvant: Int?,
    flasqueArriere: Int?,
    porteeRAvant: Int?,
    porteeRArriere: Int?,
    boutArbre: Boolean?,
    rondelleElastique: Boolean?,
    refRoulementAvant: Array<String>?,
    refRoulementArriere: Array<String>?,
    typeRoulementAvant: Array<String>?,
    typeRoulementArriere: Array<String>?,
    refJointAvant: String?,
    refJointArriere: String?,
    typeJointAvant: Boolean?,
    typeJointArriere: Boolean?,
    ventilateur: Int?,
    capotV: Int?,
    socleBoiteABorne: Int?,
    capotBoiteABorne: Int?,
    plaqueABorne: Int?,
    presenceSondes: Boolean?,
    typeSondes: String?,
    equilibrage: Boolean?,
    peinture: String?,
    var isolementPhaseMasseStatorUM: Float?,
    var isolementPhaseMasseStatorVM: Float?,
    var isolementPhaseMasseStatorWM: Float?,
    var isolementPhasePhaseStatorUV: Float?,
    var isolementPhasePhaseStatorVW: Float?,
    var isolementPhasePhaseStatorUW: Float?,
    var resistanceStatorU: Float?,
    var resistanceStatorV: Float?,
    var resistanceStatorW: Float?,
    var tensionU: Float?,
    var tensionV: Float?,
    var tensionW: Float?,
    var intensiteU: Float?,
    var intensiteV: Float?,
    var intensiteW: Float?,
    var dureeEssai: Float?,
) : DemontageMoteur(
    idFiche,
    numDevis,
    numFiche,
    type,
    statut,
    client,
    contact,
    telContact,
    techniciens,
    resp,
    dateDebut,
    dureeTotale,
    observation,
    photos,
    6,
    typeMoteur,
    marque,
    numSerie,
    puissance,
    bride,
    vitesse,
    arbreSortantEntrant, //arbre sortant ou rentrant
    accouplement,
    coteAccouplement,
    clavette,
    aspect,
    aspectInterieur,
    couplage,
    flasqueAvant,
    flasqueArriere,
    porteeRAvant,
    porteeRArriere,
    boutArbre,
    rondelleElastique,
    refRoulementAvant,
    refRoulementArriere,
    typeRoulementAvant,
    typeRoulementArriere,
    refJointAvant,
    refJointArriere,
    typeJointAvant,
    typeJointArriere,
    ventilateur,
    capotV,
    socleBoiteABorne,
    capotBoiteABorne,
    plaqueABorne,
    presenceSondes,
    typeSondes,
    equilibrage,
    peinture
) {
    override fun toString(): String {
        return "${_id} - ${numDevis} + - ${
            numFiche}  - ${
            status}  - ${
            client!!._id}  - ${
            contact}  - ${
            telContact}  - ${
            dateDebut}  - ${
            dureeTotale}  - ${
            observations}  - ${
            6}  - ${
            marque}  - ${
            numSerie}  - ${
            puissance}  - ${
            bride}  - ${
            vitesse}  - ${
            arbreSortantEntrant}  - ${
            accouplement}  - ${
            coteAccouplement}  - ${
            clavette}  - ${
            aspect}  - ${
            aspectInterieur}  - ${
            couplage}  - ${
            flasqueAvant}  - ${
            flasqueArriere}  - ${
            porteeRArriere}  - ${
            porteeRAvant}  - ${
            boutArbre}  - ${
            rondelleElastique}  - ${
            refRoulementAvant}  - ${
            refRoulementArriere}  - ${
            typeRoulementAvant}  - ${
            typeRoulementArriere}  - ${
            refJointAvant}  - ${
            refJointArriere}  - ${
            typeJointAvant}  - ${
            typeJointArriere}  - ${
            ventilateur}  - ${
            capotV}  - ${
            socleBoiteABorne}  - ${
            capotBoiteABorne}  - ${
            plaqueABorne}  - ${
            presenceSondes}  - ${
            typeSondes}  - ${
            equilibrage}  - ${
            peinture}  - ${
            isolementPhaseMasseStatorUM}  - ${
            isolementPhaseMasseStatorVM}  - ${
            isolementPhaseMasseStatorWM}  - ${
            isolementPhasePhaseStatorUV}  - ${
            isolementPhasePhaseStatorVW}  - ${
            isolementPhasePhaseStatorUW}  - ${
            resistanceStatorU}  - ${
            resistanceStatorV}  - ${
            resistanceStatorW}  - ${
            tensionU}  - ${
            tensionV}  - ${
            tensionW}  - ${
            intensiteU}  - ${
            intensiteV}  - ${
            intensiteW}  - ${
            dureeEssai}"
    }
    fun toEntity() : DemontageTriphaseEntity{
        return DemontageTriphaseEntity(
            _id,
            numDevis,
            numFiche,
            status,
            client!!._id,
            contact,
            telContact,
            dateDebut,
            dureeTotale,
            observations,
            photos,
            6,
            typeMoteur,
            marque,
            numSerie,
            puissance,
            bride,
            vitesse,
            arbreSortantEntrant,
            accouplement,
            coteAccouplement,
            clavette,
            aspect,
            aspectInterieur,
            couplage,
            flasqueAvant,
            flasqueArriere,
            porteeRArriere,
            porteeRAvant,
            boutArbre,
            rondelleElastique,
            refRoulementAvant,
            refRoulementArriere,
            typeRoulementAvant,
            typeRoulementArriere,
            refJointAvant,
            refJointArriere,
            typeJointAvant,
            typeJointArriere,
            ventilateur,
            capotV,
            socleBoiteABorne,
            capotBoiteABorne,
            plaqueABorne,
            presenceSondes,
            typeSondes,
            equilibrage,
            peinture,
            isolementPhaseMasseStatorUM,
            isolementPhaseMasseStatorVM,
            isolementPhaseMasseStatorWM,
            isolementPhasePhaseStatorUV,
            isolementPhasePhaseStatorVW,
            isolementPhasePhaseStatorUW,
            resistanceStatorU,
            resistanceStatorV,
            resistanceStatorW,
            tensionU,
            tensionV,
            tensionW,
            intensiteU,
            intensiteV,
            intensiteW,
            dureeEssai
        )
    }
}

class DemontageRotorBobine(
    idFiche: String,
    numDevis: String?,
    numFiche: String?,
    type: Long?,
    statut: Long?,
    client: Client?,
    contact: String?,
    telContact: String?,
    techniciens: Array<User>?,
    resp: User?,
    dateDebut: Date?,
    dureeTotale: Long?,
    observation: String?,
    photos: Array<String>?,
    typeMoteur: String?,
    marque: String?,
    numSerie: String?,
    puissance: Float?,
    bride: Float?,
    vitesse: Float?,
    arbreSortantEntrant: Boolean?, //arbre sortant ou rentrant
    accouplement: Boolean?,
    coteAccouplement: String?,
    clavette: Boolean?,
    aspect: Int?,
    aspectInterieur: Int?,
    couplage: String?,
    flasqueAvant: Int?,
    flasqueArriere: Int?,
    porteeRAvant: Int?,
    porteeRArriere: Int?,
    boutArbre: Boolean?,
    rondelleElastique: Boolean?,
    refRoulementAvant: Array<String>?,
    refRoulementArriere: Array<String>?,
    typeRoulementAvant: Array<String>?,
    typeRoulementArriere: Array<String>?,
    refJointAvant: String?,
    refJointArriere: String?,
    typeJointAvant: Boolean?,
    typeJointArriere: Boolean?,
    ventilateur: Int?,
    capotV: Int?,
    socleBoiteABorne: Int?,
    capotBoiteABorne: Int?,
    plaqueABorne: Int?,
    presenceSondes: Boolean?,
    typeSondes: String?,
    equilibrage: Boolean?,
    peinture: String?,
    var isolementPhaseMasseStatorUM	: Float?,
    var isolementPhaseMasseStatorVM	: Float?,
    var isolementPhaseMasseStatorWM	: Float?,
    var isolementPhaseMasseRotorB1M	: Float?,
    var isolementPhaseMasseRotorB2M	: Float?,
    var isolementPhaseMasseRotorB3M	: Float?,
    var isolementPhaseMassePorteBalaisM	: Float?,
    var isolementPhasePhaseStatorUV	: Float?,
    var isolementPhasePhaseStatorVW	: Float?,
    var isolementPhasePhaseStatorUW	: Float?,
    var resistanceStatorU	: Float?,
    var resistanceStatorV	: Float?,
    var resistanceStatorW	: Float?,
    var resistanceRotorB1B2	: Float?,
    var resistanceRotorB2B2	: Float?,
    var resistanceRotorB1B3	: Float?,
    var tensionU	: Float?,
    var tensionV	: Float?,
    var tensionW	: Float?,
    var tensionRotor	: Float?,
    var intensiteU	: Float?,
    var intensiteV	: Float?,
    var intensiteW	: Float?,
    var intensiteRotor	: Float?,
    var dureeEssai	: Int?
) : DemontageMoteur(
    idFiche,
    numDevis,
    numFiche,
    type,
    statut,
    client,
    contact,
    telContact,
    techniciens,
    resp,
    dateDebut,
    dureeTotale,
    observation,
    photos,
    4,
    typeMoteur,
    marque,
    numSerie,
    puissance,
    bride,
    vitesse,
    arbreSortantEntrant, //arbre sortant ou rentrant
    accouplement,
    coteAccouplement,
    clavette,
    aspect,
    aspectInterieur,
    couplage,
    flasqueAvant,
    flasqueArriere,
    porteeRAvant,
    porteeRArriere,
    boutArbre,
    rondelleElastique,
    refRoulementAvant,
    refRoulementArriere,
    typeRoulementAvant,
    typeRoulementArriere,
    refJointAvant,
    refJointArriere,
    typeJointAvant,
    typeJointArriere,
    ventilateur,
    capotV,
    socleBoiteABorne,
    capotBoiteABorne,
    plaqueABorne,
    presenceSondes,
    typeSondes,
    equilibrage,
    peinture
) {
    fun toEntity(): DemontageRotorBEntity{
        return DemontageRotorBEntity(
            _id,
            numDevis,
            numFiche,
            2,
            client!!._id,
            contact,
            telContact,
            dateDebut,
            dureeTotale,
            observations,
            photos,
            4,
            typeMoteur,
            marque,
            numSerie,
            puissance,
            bride,
            vitesse,
            arbreSortantEntrant,
            accouplement,
            coteAccouplement,
            clavette,
            aspect,
            aspectInterieur,
            couplage,
            flasqueAvant,
            flasqueArriere,
            porteeRArriere,
            porteeRAvant,
            boutArbre,
            rondelleElastique,
            refRoulementAvant,
            refRoulementArriere,
            typeRoulementAvant,
            typeRoulementArriere,
            refJointAvant,
            refJointArriere,
            typeJointAvant,
            typeJointArriere,
            ventilateur,
            capotV,
            socleBoiteABorne,
            capotBoiteABorne,
            plaqueABorne,
            presenceSondes,
            typeSondes,
            equilibrage,
            peinture,
            isolementPhaseMasseStatorUM	,
            isolementPhaseMasseStatorVM	,
            isolementPhaseMasseStatorWM	,
            isolementPhaseMasseRotorB1M	,
            isolementPhaseMasseRotorB2M	,
            isolementPhaseMasseRotorB3M	,
            isolementPhaseMassePorteBalaisM	,
            isolementPhasePhaseStatorUV	,
            isolementPhasePhaseStatorVW	,
            isolementPhasePhaseStatorUW	,
            resistanceStatorU	,
            resistanceStatorV	,
            resistanceStatorW	,
            resistanceRotorB1B2	,
            resistanceRotorB2B2	,
            resistanceRotorB1B3	,
            tensionU	,
            tensionV	,
            tensionW	,
            tensionRotor	,
            intensiteU	,
            intensiteV	,
            intensiteW	,
            intensiteRotor	,
            dureeEssai
        )
    }
}

class CourantContinu(
    idFiche: String,
    numDevis: String?,
    numFiche: String?,
    type: Long?,
    statut: Long?,
    client: Client?,
    contact: String?,
    telContact: String?,
    techniciens: Array<User>?,
    resp: User?,
    dateDebut: Date?,
    dureeTotale: Long?,
    observation: String?,
    photos: Array<String>?,
    typeMoteur: String?,
    marque: String?,
    numSerie: String?,
    puissance: Float?,
    bride: Float?,
    vitesse: Float?,
    arbreSortantEntrant: Boolean?, //arbre sortant ou rentrant
    accouplement: Boolean?,
    coteAccouplement: String?,
    clavette: Boolean?,
    aspect: Int?,
    aspectInterieur: Int?,
    couplage: String?,
    flasqueAvant: Int?,
    flasqueArriere: Int?,
    porteeRAvant: Int?,
    porteeRArriere: Int?,
    boutArbre: Boolean?,
    rondelleElastique: Boolean?,
    refRoulementAvant: Array<String>?,
    refRoulementArriere: Array<String>?,
    typeRoulementAvant: Array<String>?,
    typeRoulementArriere: Array<String>?,
    refJointAvant: String?,
    refJointArriere: String?,
    typeJointAvant: Boolean?,
    typeJointArriere: Boolean?,
    ventilateur: Int?,
    capotV: Int?,
    socleBoiteABorne: Int?,
    capotBoiteABorne: Int?,
    plaqueABorne: Int?,
    presenceSondes: Boolean?,
    typeSondes: String?,
    equilibrage: Boolean?,
    peinture: String?,
    var isolationMasseInduit: Float?,
    var isolationMassePolesPrincipaux: Float?,
    var isolationMassePolesAuxilliaires: Float?,
    var isolationMassePolesCompensatoires: Float?,
    var isolationMassePorteBalais: Float?,
    var resistanceInduit: Float?,
    var resistancePP: Float?,
    var resistancePA: Float?,
    var resistancePC: Float?,
    /* essais dynamiques */
    var tensionInduit: Float?,
    var intensiteInduit: Float?,
    var tensionExcitation: Float?,
    var intensiteExcitation: Float?,
    ) : DemontageMoteur(
    idFiche,
    numDevis,
    numFiche,
    type,
    statut,
    client,
    contact,
    telContact,
    techniciens,
    resp,
    dateDebut,
    dureeTotale,
    observation,
    photos,
    5,
    typeMoteur,
    marque,
    numSerie,
    puissance,
    bride,
    vitesse,
    arbreSortantEntrant, //arbre sortant ou rentrant
    accouplement,
    coteAccouplement,
    clavette,
    aspect,
    aspectInterieur,
    couplage,
    flasqueAvant,
    flasqueArriere,
    porteeRAvant,
    porteeRArriere,
    boutArbre,
    rondelleElastique,
    refRoulementAvant,
    refRoulementArriere,
    typeRoulementAvant,
    typeRoulementArriere,
    refJointAvant,
    refJointArriere,
    typeJointAvant,
    typeJointArriere,
    ventilateur,
    capotV,
    socleBoiteABorne,
    capotBoiteABorne,
    plaqueABorne,
    presenceSondes,
    typeSondes,
    equilibrage,
    peinture
) {
        fun toEntity(): DemontageCCEntity{
            return DemontageCCEntity (
                _id,
                numDevis,
                numFiche,
                2,
                client!!._id,
                contact,
                telContact,
                dateDebut,
                dureeTotale,
                observations,
                photos,
                5,
                typeMoteur,
                marque,
                numSerie,
                puissance,
                bride,
                vitesse,
                arbreSortantEntrant,
                accouplement,
                coteAccouplement,
                clavette,
                aspect,
                aspectInterieur,
                couplage,
                flasqueAvant,
                flasqueArriere,
                porteeRArriere,
                porteeRAvant,
                boutArbre,
                rondelleElastique,
                refRoulementAvant,
                refRoulementArriere,
                typeRoulementAvant,
                typeRoulementArriere,
                refJointAvant,
                refJointArriere,
                typeJointAvant,
                typeJointArriere,
                ventilateur,
                capotV,
                socleBoiteABorne,
                capotBoiteABorne,
                plaqueABorne,
                presenceSondes,
                typeSondes,
                equilibrage,
                peinture,
                isolationMasseInduit,
                isolationMassePolesPrincipaux,
                isolationMassePolesAuxilliaires,
                isolationMassePolesCompensatoires,
                isolationMassePorteBalais,
                resistanceInduit,
                resistancePP,
                resistancePA,
                resistancePC,
                /* essais dynamiques */
                tensionInduit,
                intensiteInduit,
                tensionExcitation,
                intensiteExcitation
            )
        }
    }

class DemontageAlternateur(
    idFiche: String,
    numDevis: String?,
    numFiche: String?,
    type: Long?,
    statut: Long?,
    client: Client?,
    contact: String?,
    telContact: String?,
    techniciens: Array<User>?,
    resp: User?,
    dateDebut: Date?,
    dureeTotale: Long?,
    observation: String?,
    photos: Array<String>?,
    typeMoteur: String?,
    marque: String?,
    numSerie: String?,
    puissance: Float?,
    bride: Float?,
    vitesse: Float?,
    arbreSortantEntrant: Boolean?, //arbre sortant ou rentrant
    accouplement: Boolean?,
    coteAccouplement: String?,
    clavette: Boolean?,
    aspect: Int?,
    aspectInterieur: Int?,
    couplage: String?,
    flasqueAvant: Int?,
    flasqueArriere: Int?,
    porteeRAvant: Int?,
    porteeRArriere: Int?,
    boutArbre: Boolean?,
    rondelleElastique: Boolean?,
    refRoulementAvant: Array<String>?,
    refRoulementArriere: Array<String>?,
    typeRoulementAvant: Array<String>?,
    typeRoulementArriere: Array<String>?,
    refJointAvant: String?,
    refJointArriere: String?,
    typeJointAvant: Boolean?,
    typeJointArriere: Boolean?,
    ventilateur: Int?,
    capotV: Int?,
    socleBoiteABorne: Int?,
    capotBoiteABorne: Int?,
    plaqueABorne: Int?,
    presenceSondes: Boolean?,
    typeSondes: String?,
    equilibrage: Boolean?,
    peinture: String?,
    var isolementMasseStatorPrincipalU: Float?,
    var isolementMasseStatorPrincipalV: Float?,
    var isolementMasseStatorPrincipalW	: Float?,
    var isolementMasseRotorPrincipal	: Float?,
    var isolementMasseStatorExcitation	: Float?,
    var isolementMasseRotorExcitation : Float?,
    var resistanceStatorPrincipalU	: Float?,
    var resistanceStatorPrincipalV	: Float?,
    var resistanceStatorPrincipalW	: Float?,
    var resistanceRotorPrincipal	: Float?,
    var resistanceStatorExcitation	: Float?,
    var resistanceRotorExcitation	: Float?,
    var isolementPhasePhaseStatorPrincipalUV	: Float?,
    var isolementPhasePhaseStatorPrincipalVW	: Float?,
    var isolementPhasePhaseStatorPrincipalUW	: Float?,
    var testDiode : Boolean?,
    var tensionU	: Float?,
    var tensionV	: Float?,
    var tensionW	: Float?,
    var intensiteU	: Float?,
    var intensiteV	: Float?,
    var intensiteW	: Float?,
    var tensionExcitation	: Float?,
    var intensiteExcitation	: Float?,
) : DemontageMoteur(
    idFiche,
    numDevis,
    numFiche,
    type,
    statut,
    client,
    contact,
    telContact,
    techniciens,
    resp,
    dateDebut,
    dureeTotale,
    observation,
    photos,
    3,
    typeMoteur,
    marque,
    numSerie,
    puissance,
    bride,
    vitesse,
    arbreSortantEntrant, //arbre sortant ou rentrant
    accouplement,
    coteAccouplement,
    clavette,
    aspect,
    aspectInterieur,
    couplage,
    flasqueAvant,
    flasqueArriere,
    porteeRAvant,
    porteeRArriere,
    boutArbre,
    rondelleElastique,
    refRoulementAvant,
    refRoulementArriere,
    typeRoulementAvant,
    typeRoulementArriere,
    refJointAvant,
    refJointArriere,
    typeJointAvant,
    typeJointArriere,
    ventilateur,
    capotV,
    socleBoiteABorne,
    capotBoiteABorne,
    plaqueABorne,
    presenceSondes,
    typeSondes,
    equilibrage,
    peinture) {
    fun toEntity(): DemontageAlternateurEntity {
        return DemontageAlternateurEntity(
            _id,
            numDevis,
            numFiche,
            2,
            client!!._id,
            contact,
            telContact,
            dateDebut,
            dureeTotale,
            observations,
            photos,
            3,
            typeMoteur,
            marque,
            numSerie,
            puissance,
            bride,
            vitesse,
            arbreSortantEntrant,
            accouplement,
            coteAccouplement,
            clavette,
            aspect,
            aspectInterieur,
            couplage,
            flasqueAvant,
            flasqueArriere,
            porteeRArriere,
            porteeRAvant,
            boutArbre,
            rondelleElastique,
            refRoulementAvant,
            refRoulementArriere,
            typeRoulementAvant,
            typeRoulementArriere,
            refJointAvant,
            refJointArriere,
            typeJointAvant,
            typeJointArriere,
            ventilateur,
            capotV,
            socleBoiteABorne,
            capotBoiteABorne,
            plaqueABorne,
            presenceSondes,
            typeSondes,
            equilibrage,
            peinture,
            isolementMasseStatorPrincipalU,
            isolementMasseStatorPrincipalV,
            isolementMasseStatorPrincipalW,
            isolementMasseRotorPrincipal,
            isolementMasseStatorExcitation,
            isolementMasseRotorExcitation,
            resistanceStatorPrincipalU,
            resistanceStatorPrincipalV,
            resistanceStatorPrincipalW,
            resistanceRotorPrincipal,
            resistanceStatorExcitation,
            resistanceRotorExcitation,
            isolementPhasePhaseStatorPrincipalUV,
            isolementPhasePhaseStatorPrincipalVW,
            isolementPhasePhaseStatorPrincipalUW,
            testDiode,
            tensionU,
            tensionV,
            tensionW,
            intensiteU,
            intensiteV,
            intensiteW,
            tensionExcitation,
            intensiteExcitation
        )
    }
}