package com.example.applicationstb.localdatabase

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.applicationstb.model.Client
import com.example.applicationstb.model.FicheDemontage
import com.example.applicationstb.model.Joint
import com.example.applicationstb.model.Roulement
import java.util.*

@Entity(tableName = "demontage")
class DemontageEntity (
    @PrimaryKey
    var _id: String,
    var numDevis: String?,
    var numFiche: String?,
    var statut: Long?,
    var client: String,
    var contact: String?,
    var telContact: String?,
    var dateDebut: Date?,
    var dureeTotale: Long?,
    var observation: String?,
    var photos:Array<String>?,
    var subtype: Int,
    var marque: String?,
    var typeMoteur: String?,
    var numSerie: String?,
    var arbreSortantEntrant: Boolean?,
    var accouplement: Boolean?,
    var coteAccouplement: String?,
    var clavette: Boolean?,
    var aspect: Int?,
    var aspectInterieur: Int?,
    var flasqueAvant:Int?,
    var flasqueArriere: Int?,
    var porteeRAvant: Int?,
    var porteeRArriere: Int?,
    var boutArbre: Boolean?,
    var refRoulementAvant: Array<String>?,
    var refRoulementArriere: Array<String>?,
    var typeRoulementAvant: Array<String>?,
    var typeRoulementArriere: Array<String>?,
    var refJointAvant: String?,
    var refJointArriere: String?,
    var typeJointAvant: Boolean?,
    var typeJointArriere: Boolean?,
    // fiches 2,3,4,5,6,7
    var puissance: String?,
    var bride: String?,
    var vitesse: String?,
    var couplage: String?,
    var rondelleElastique: Boolean?,
    var ventilateur: Int?,
    var capotV: Int?,
    var socleBoiteABorne: Int?,
    var capotBoiteABorne: Int?,
    var plaqueABorne: Int?,
    var presenceSondes: Boolean?,
    var typeSondes: String?,
    var equilibrage: Boolean?,
    var peinture: String?,
    var tensionU: String?,
    var tensionV: String?,
    var tensionW: String?,
    // fiches 3,4,5,6,7
    var isolementPhase: String?,
    //fiches 1
    var fluide: String?,
    var sensRotation: Boolean?,
    var typeRessort: Int?,
    var typeJoint: String?,
    var matiere: Int?,
    var diametreArbre: String?,
    var diametreExtPR: String?,
    var diametreExtPF: String?,
    var epaisseurPF: String?,
    var longueurRotativeNonComprimee: String?,
    var longueurRotativeComprimee: String?,
    var longueurRotativeTravail: String?,
    var typeJoint2: String?,
    var matiere2: Int?,
    var diametreArbre2: String?,
    var diametreExtPR2: String?,
    var diametreExtPF2: String?,
    var epaisseurPF2: String?,
    var longueurRotativeNonComprimee2: String?,
    var longueurRotativeComprimee2: String?,
    var longueurRotativeTravail2: String?,
    // fiches 2
    var resistanceTravail: String?,
    var resistanceDemarrage: String?,
    var valeurCondensateur: String?,
    // fiches 3
    var isolementMasseStatorPrincipalU: String?,
    var isolementMasseStatorPrincipalV: String?,
    var isolementMasseStatorPrincipalW: String?,
    var isolementMasseRotorPrincipal: String?,
    var isolementMasseStatorExcitation: String?,
    var isolementMasseRotorExcitation: String?,
    var resistanceRotorPrincipal: String?,
    var resistanceStatorExcitation: String?,
    var resistanceRotorExcitation: String?,
    var testDiode: Boolean?,
    // fiche 5
    var isolementMasseInduit: String?,
    var isolementMassePolesPrincipaux: String?,
    var isolementMassePolesAuxilliaires: String?,
    var isolementMassePolesCompensatoires: String?,
    var isolementMassePorteBalais: String?,
    var resistanceInduit: String?,
    var resistancePP: String?,
    var resistancePA: String?,
    var resistancePC: String?,
    // fiche 6
    var isolementPhaseMasseStatorUM: String?,
    var isolementPhaseMasseStatorVM: String?,
    var isolementPhaseMasseStatorWM: String?,
    var isolementPhasePhaseStatorUV: String?,
    var isolementPhasePhaseStatorVW: String?,
    var isolementPhasePhaseStatorUW: String?,
    var resistanceStatorU: String?,
    var resistanceStatorV: String?,
    var resistanceStatorW: String?,
    //fiche 7
    var typeMotopompe: Int?,
    // fiche 8
    var trMinute: String?,
    var modele: String?,
    var indiceReduction: String?,
    var typeHuile: String?,
    var quantiteHuile: String?,
    var roulements: MutableList<Roulement>?,
    var joints: MutableList<Joint>?,
    var typeMotoreducteur: Int?
) {
    fun toFicheDemontage(): FicheDemontage{
        return FicheDemontage(
            _id,
            numDevis,
            numFiche,
            2,
            statut,
            Client(client,null,null,null, null),
            contact,
            telContact,
            null,
            null,
            dateDebut,
            dureeTotale,
            observation,
            photos,
            subtype,
            marque,
            typeMoteur,
            numSerie,
            arbreSortantEntrant,
            accouplement,
            coteAccouplement,
            clavette,
            aspect,
            aspectInterieur,
            flasqueAvant,
            flasqueArriere,
            porteeRArriere,
            porteeRAvant,
            boutArbre,
            refRoulementAvant,
            refRoulementArriere,
            typeRoulementAvant,
            typeRoulementArriere,
            refJointAvant,
            refJointArriere,
            typeJointAvant,
            typeJointArriere,
            puissance,
            bride,
            vitesse,
            couplage,
            rondelleElastique,
            ventilateur,
            capotV,
            socleBoiteABorne,
            capotBoiteABorne,
            plaqueABorne,
            presenceSondes,
            typeSondes,
            equilibrage,
            peinture,
            tensionU,
            tensionV,
            tensionW,
            isolementPhase,
            fluide,
            sensRotation,
            typeRessort,
            typeJoint,
            matiere,
            diametreArbre,
            diametreExtPR,
            diametreExtPF,
            epaisseurPF,
            longueurRotativeNonComprimee,
            longueurRotativeComprimee,
            longueurRotativeTravail,
            typeJoint2,
            matiere2,
            diametreArbre2,
            diametreExtPR2,
            diametreExtPF2,
            epaisseurPF2,
            longueurRotativeNonComprimee2,
            longueurRotativeComprimee2,
            longueurRotativeTravail2,
            resistanceTravail,
            resistanceDemarrage,
            valeurCondensateur,
            isolementMasseStatorPrincipalU,
            isolementMasseStatorPrincipalV,
            isolementMasseStatorPrincipalW,
            isolementMasseRotorPrincipal,
            isolementMasseStatorExcitation,
            isolementMasseRotorExcitation,
            resistanceRotorPrincipal,
            resistanceStatorExcitation,
            resistanceRotorExcitation,
            testDiode,
            isolementMasseInduit,
            isolementMassePolesPrincipaux,
            isolementMassePolesAuxilliaires,
            isolementMassePolesCompensatoires,
            isolementMassePorteBalais,
            resistanceInduit,
            resistancePP,
            resistancePA,
            resistancePC,
            isolementPhaseMasseStatorUM,
            isolementPhaseMasseStatorVM,
            isolementPhaseMasseStatorWM,
            isolementPhasePhaseStatorUV,
            isolementPhasePhaseStatorVW,
            isolementPhasePhaseStatorUW,
            resistanceStatorU,
            resistanceStatorV,
            resistanceStatorW,
            typeMotopompe,
            trMinute,
            modele,
            indiceReduction,
            typeHuile,
            quantiteHuile,
            roulements,
            joints,
            typeMotoreducteur
        )
    }
}