package com.example.applicationstb.localdatabase

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.applicationstb.model.Client
import com.example.applicationstb.model.DemontageMotoreducteur
import com.example.applicationstb.model.Joint
import com.example.applicationstb.model.Roulement
import java.util.*

@Entity(tableName = "demontage_motoreducteur")
data class DemontageMotoreducteurEntity(
    @PrimaryKey var _id: String,
    var numDevis: String?,
    var numFiche: String?,
    var statut: Long?,
    var client: String,
    var contact: String?,
    var telContact: String?,
    var dateDebut: Date?,
    var dureeTotale: Long?,
    var observation: String?,
    var photos: Array<String>?,
    var typeFicheDemontage: Int,
    var typeMoteur: String?,
    var marque: String?,
    var numSerie: String?,
    var puissance: Float?,
    var bride: Float?,
    var vitesse: Float?,
    var arbreSortantEntrant: Boolean?, //arbre sortant ou rentrant
    var accouplement: Boolean?,
    var coteAccouplement: String?,
    var clavette: Boolean?,
    var aspect: Int?,
    var aspectInterieur: Int?,
    var couplage: String?,
    var flasqueAvant: Int?,
    var flasqueArriere: Int?,
    var porteeRAvant: Int?,
    var porteeRArriere: Int?,
    var boutArbre: Boolean?,
    var rondelleElastique: Boolean?,
    var refRoulementAvant: Array<String>?,
    var refRoulementArriere: Array<String>?,
    var typeRoulementAvant: Array<String>?,
    var typeRoulementArriere: Array<String>?,
    var refJointAvant: String?,
    var refJointArriere: String?,
    var typeJointAvant: Boolean?,
    var typeJointArriere: Boolean?,
    var ventilateur: Int?,
    var capotV: Int?,
    var socleBoiteABorne: Int?,
    var capotBoiteABorne: Int?,
    var plaqueABorne: Int?,
    var presenceSondes: Boolean?,
    var typeSondes: String?,
    var equilibrage: Boolean?,
    var peinture: String?,
    var typeMotoreducteur: String?,
    var trMinute: Float?,
    var modele: String?,
    var indiceReduction: String?,
    var typeHuile: String?,
    var quantiteHuile: Float?,
    var roulements: MutableList<Roulement>?,
    var joints: MutableList<Joint>?,
    var isolementPhaseMasseStatorUM: Float?,
    var isolementPhaseMasseStatorVM: Float?,
    var isolementPhaseMasseStatorWM: Float?,
    var isolementPhasePhaseStatorUV: Float?,
    var isolementPhasePhaseStatorVW: Float?,
    var isolementPhasePhaseStatorUW: Float?,
    var resistanceStatorU: Float?,
    var resistanceStatorV: Float?,
    var resistanceStatorW: Float?,
    var tensionU: Float?,
    var tensionV: Float?,
    var tensionW: Float?,
    var intensiteU: Float?,
    var intensiteV: Float?,
    var intensiteW: Float?,
    var dureeEssai: Float?,
    var isolementPhaseMasse: Float?,
    var resistanceTravail: Float?,
    var resistanceDemarrage: Float?,
    var valeurCondensateur: Float?,
    var tension: Float?,
    var intensite: Float?
) {
    fun toDemontageMotoreducteur(): DemontageMotoreducteur{
        return DemontageMotoreducteur(
            _id,
            numDevis,
            numFiche,
            2,
            statut,
            Client(client,null,null,null, null),
            contact,
            telContact,
            null,
            null,
            dateDebut,
            dureeTotale,
            observation,
            photos,
            typeMoteur,
            marque,
            numSerie,
            puissance,
            bride,
            vitesse,
            arbreSortantEntrant,
            accouplement,
            coteAccouplement,
            clavette,
            aspect,
            aspectInterieur,
            couplage,
            flasqueAvant,
            flasqueArriere,
            porteeRArriere,
            porteeRAvant,
            boutArbre,
            rondelleElastique,
            refRoulementAvant,
            refRoulementArriere,
            typeRoulementAvant,
            typeRoulementArriere,
            refJointAvant,
            refJointArriere,
            typeJointAvant,
            typeJointArriere,
            ventilateur,
            capotV,
            socleBoiteABorne,
            capotBoiteABorne,
            plaqueABorne,
            presenceSondes,
            typeSondes,
            equilibrage,
            peinture,
            typeMotoreducteur,
            trMinute,
            modele,
            indiceReduction,
            typeHuile,
            quantiteHuile,
            roulements,
            joints,
            isolementPhaseMasseStatorUM,
            isolementPhaseMasseStatorVM,
            isolementPhaseMasseStatorWM,
            isolementPhasePhaseStatorUV,
            isolementPhasePhaseStatorVW,
            isolementPhasePhaseStatorUW,
            resistanceStatorU,
            resistanceStatorV,
            resistanceStatorW,
            tensionU,
            tensionV,
            tensionW,
            intensiteU,
            intensiteV,
            intensiteW,
            dureeEssai,
            isolementPhaseMasse,
            resistanceTravail,
            resistanceDemarrage,
            valeurCondensateur,
            tension,
            intensite
        )
    }
}
