package com.example.applicationstb.localdatabase

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.applicationstb.model.Client
import com.example.applicationstb.model.DemontagePompe
import java.util.*

@Entity(tableName = "demontage_pompe")
data class DemoPompeEntity (
    @PrimaryKey var _id: String,
    var numDevis: String?,
    var numFiche: String?,
    var statut: Long?,
    var client: String,
    var contact: String?,
    var telContact: String?,
    var dateDebut: Date?,
    var dureeTotale: Long?,
    var observation: String?,
    var photos:Array<String>?,
    var typeFicheDemontage: Int,
    var typeMoteur: String?,
    var marque: String?,
    var numSerie: String?,
    var fluide: String?,
    var sensRotation: Boolean?,
    var typeRessort: Int?,
    var typeJoint: String?,
    var matiere: Int?,
    var diametreArbre:String?,
    var diametreExtPR:String?,
    var diametreExtPF:String?,
    var epaisseurPF:String?,
    var longueurRotativeNonComprimee:String?,
    var longueurRotativeComprimee:String?,
    var longueurRotativeTravail:String?
) {
    fun toDemoPompe(): DemontagePompe{
        return DemontagePompe(
        _id,
        numDevis,
        numFiche,
        2,
        statut,
        Client(client,null,null,null, null),
        contact,
        telContact,
        null,
        null,
        dateDebut,
        dureeTotale,
        observation,
        photos,
        typeMoteur,
        marque,
        numSerie,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        fluide,
        sensRotation,
        typeRessort,
        typeJoint,
        matiere,
        diametreArbre,
        diametreExtPR,
        diametreExtPF,
        epaisseurPF,
        longueurRotativeNonComprimee,
        longueurRotativeComprimee,
        longueurRotativeTravail
        )}
}